name: Integration test

on:
  push:
    branches:
      - '**'

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Create .env
        run: >
              echo "TRAFIKVERKET_API_KEY = '016e6506181f4600bc1f9632f344b013'
              ATLAS_USERNAME='admin'
              ATLAS_PASSWORD='AGwNJ6LBT47rjCzl'" > .env
        env:
          CI: true
      - name: TypeScript check
        run: npm run test2
        env:
          CI: true
